apiVersion: apps/v1
kind: Deployment
metadata:
  name: hfdfes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hfdfes
  template:
    metadata:
      labels:
        app: hfdfes
    spec:
      containers:
      - image: okteto.dev/hfdfes:latest
        name: hfdfes
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "104ff089-ce18-49f8-b015-9d644a1ddd61"
        - name: Vless_Path
          value: "/vl756tw3ew"
        - name: Vmess_UUID
          value: "104ff089-ce18-49f8-b015-9d644a1ddd61"
        - name: Vmess_Path
          value: "/vm455fere4"
        - name: Share_Path
          value: "/v2link"
